### PR TITLE
Removed workaround for ChromeOS bug

### LINKED ISSUE #283: Extra characters input when using modifier flags
An example, using the default Model01-Firmware:

1. Press key `fn`
2. Press key `C`
3. Press and release key `U` (`{` on `FUNCTION` layer)
4. Repeat step 3 several times
5. Release all keys

…the output I see in a terminal on both macOS and Linux is as follows:
```text
ccccccccC{C{C{C{
```

If, instead, I do this:

1. Press key `fn`
2. Press key `C`
3. Press key `shift`
4. Press and release key `O` (`[` on `FUNCTION` layer)
5. Repeat steps 3 & 4 several times
6. Release all keys

…the output is the expected:
```text
cccccccc{{{{{
```

After holding a printable key, when the next key is typed, the previous one is masked at some level by the host, so the `c` stops repeating, but when a key with the `SHIFT_HELD` flag is pressed, an extra modified character for the held key appears in the output.

### PR DESCRIPTION
**Pull request by gedankenexperimenter**
This change should be merged if [KeyboardioHID#29](https://github.com/keyboardio/KeyboardioHID/pull/29) is accepted. That PR also fixes the problem with ChromeOS (and Windows Remote Desktop), but doesn't suffer from the same scan order problem that the solution here had.

Fixes [Kaleidoscope#283](https://github.com/keyboardio/Kaleidoscope/issues/283)

### CODE REVIEW

**Comment by gedankenexperimenter** [comment]
Don't merge this change unless [KeyboardioHID#29](https://github.com/keyboardio/KeyboardioHID/pull/29) is also merged.

**Comment by gedankenexperimenter** [comment]
Now that keyboardio/KeyboardioHID#29 has been merged, this should probably also be merged.

**Comment by algernon** [comment]
I'll resolve the conflict & merge this, as soon as I'm near a usable computer.

**Comment by obra** [comment]
I found a spare moment. I just resolved the conflict and merged.

**Pull request merged**
